import os
import logging
import platform
import subprocess
from typing import Literal
from pydantic import Field, computed_field, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

logger = logging.getLogger("bipod.config")

def detect_hardware_arch() -> str:
    """Returns 'arm64' or 'amd64' based on the system architecture."""
    machine = platform.machine().lower()
    if "arm" in machine or "aarch64" in machine:
        return "arm64"
    return "amd64"

def detect_gpu_presence() -> bool:
    """Checks if an NVIDIA GPU is accessible within the container."""
    try:
        # We check for nvidia-smi. If it fails, we assume CPU-only.
        subprocess.run(["nvidia-smi"], check=True, capture_output=True)
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False

def detect_gpu_vram() -> float:
    """Returns the largest visible GPU VRAM in GB, else 0.0."""
    try:
        result = subprocess.run(
            ["nvidia-smi", "--query-gpu=memory.total", "--format=csv,noheader,nounits"],
            check=True, capture_output=True, text=True
        )
        memory_values_mb = [
            float(line.strip())
            for line in result.stdout.splitlines()
            if line.strip()
        ]
        if not memory_values_mb:
            return 0.0
        # Use the largest visible GPU to avoid overestimating context on mixed hardware.
        return max(memory_values_mb) / 1024.0
    except Exception:
        return 0.0

def detect_gpu_name() -> str:
    """Returns the name of the first GPU if it exists, else 'CPU'."""
    try:
        result = subprocess.run(
            ["nvidia-smi", "--query-gpu=gpu_name", "--format=csv,noheader"],
            check=True, capture_output=True, text=True
        )
        return result.stdout.strip()
    except:
        return "CPU Mode"


def recommend_ollama_num_ctx(
    *,
    use_gpu: bool,
    gpu_vram_gb: float,
    hardware_target: Literal["amd64", "arm64"],
) -> int:
    """Choose a safe Ollama context window based on available GPU VRAM."""
    if not use_gpu:
        return 2048 if hardware_target == "arm64" else 4096
    if gpu_vram_gb < 6.0:
        return 4096
    if gpu_vram_gb < 10.0:
        return 8192
    if gpu_vram_gb < 18.0:
        return 16384
    if gpu_vram_gb < 26.0:
        return 24576
    return 32768


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env", 
        case_sensitive=True, 
        extra="ignore"
    )

    PROJECT_NAME: str = "Bipod"
    API_V1_STR: str = "/api/v1"
    
    # --- Hardware Auto-Detection ---
    # These use default_factories to probe hardware at startup
    HARDWARE_TARGET: Literal["amd64", "arm64"] = Field(default_factory=detect_hardware_arch)
    USE_GPU: bool = Field(default_factory=detect_gpu_presence)
    GPU_NAME: str = Field(default_factory=detect_gpu_name)
    GPU_VRAM: float = Field(default_factory=detect_gpu_vram) # Largest visible GPU VRAM in GB
    
    # --- Storage Paths ---
    # Use /app/data if inside container, else local ./data
    DATA_DIR: str = "/app/data" if os.path.exists("/app") else os.path.join(os.getcwd(), "data")
    
    # Root of the host filesystem (mapped via Docker)
    HOST_ROOT: str = "/host" if os.path.exists("/host") else "/"

    @computed_field
    @property
    def DOCUMENTS_DIR(self) -> str:
        return os.path.join(self.DATA_DIR, "documents")

    @computed_field
    @property
    def MEMORY_DIR(self) -> str:
        return os.path.join(self.DATA_DIR, "memory")

    @computed_field
    @property
    def VECTOR_DIR(self) -> str:
        return os.path.join(self.DATA_DIR, "vector")

    @computed_field
    @property
    def GENERATED_DIR(self) -> str:
        """Directory for files created/generated by Bipod."""
        return os.path.join(self.DATA_DIR, "generated")

    @computed_field
    @property
    def UPLOADS_DIR(self) -> str:
        """Directory for temporary user uploads."""
        return os.path.join(self.DATA_DIR, "uploads")

    
    @computed_field
    @property
    def DATABASE_URL(self) -> str:
        return f"sqlite:///{self.MEMORY_DIR}/bipod_memory.db"

    @computed_field
    @property
    def OLLAMA_BASE_URL(self) -> str:
        """Dynamic Ollama URL: 'ollama' inside Docker, 'localhost' outside."""
        import socket
        host = "ollama"
        try:
            socket.gethostbyname(host)
            return f"http://{host}:11434"
        except socket.gaierror:
            return "http://localhost:11434"

    @computed_field
    @property
    def IMAGINE_API_URL(self) -> str:
        """Dynamic Imagine URL: 'imagine' inside Docker, 'localhost' outside."""
        import socket
        host = "imagine"
        try:
            socket.gethostbyname(host)
            return f"http://{host}:3333"
        except socket.gaierror:
            return "http://localhost:3333"

    
    # Brain tiers
    SMART_MODEL: str = "qwen2.5:7b"      # Best for tool calling & precision
    HEAVY_MODEL: str = "qwen3:8b"        # High intelligence, creative baseline
    MEDIUM_MODEL: str = "llama3.2:3b"    # For standard PC / CPU fallback
    LIGHT_MODEL: str = "llama3.2:1b"     # For Pi 5 / Edge devices
    VISION_MODEL: str = "moondream"      # Specialized for image analysis
    EMBEDDING_MODEL: str = "nomic-embed-text" # Local vector embeddings

    # Coach ASR (faster-whisper)
    COACH_WHISPER_MODEL: str = "small"
    COACH_WHISPER_MODEL_PATH: str = ""
    COACH_WHISPER_DOWNLOAD_ROOT: str = ""
    COACH_WHISPER_LOCAL_FILES_ONLY: bool = True
    COACH_WHISPER_DEVICE: str = "auto"  # auto | cpu | cuda
    COACH_WHISPER_COMPUTE_TYPE: str = ""  # empty -> infer from device
    COACH_TTS_PROVIDER: str = "espeak"  # espeak | cosyvoice
    COACH_TTS_ALLOW_ESPEAK_FALLBACK: bool = True
    COACH_COSYVOICE_BASE_URL: str = "http://cosyvoice:5001"
    COACH_COSYVOICE_MODEL_ID: str = "FunAudioLLM/CosyVoice3-0.5B"
    COACH_COSYVOICE_DEVICE: str = "auto"  # auto | cpu | cuda
    COACH_COSYVOICE_LOCAL_FILES_ONLY: bool = True
    COACH_COSYVOICE_DOWNLOAD_ROOT: str = "/app/data/huggingface/hub"
    COACH_COSYVOICE_TIMEOUT_SEC: int = 60
    COACH_VOICE_SECRET_KEY: str = ""
    COACH_VOICE_LIBRARY_DIR: str = "/app/data/coach_voice_library"

    # Ollama runtime tuning
    OLLAMA_NUM_CTX: int | None = None
    OLLAMA_TEMPERATURE: float = 0.3
    OLLAMA_REPEAT_PENALTY: float = 1.1
    OLLAMA_CHAT_TIMEOUT_SEC: int = 180
    OLLAMA_TOOL_CHAT_TIMEOUT_SEC: int = 240
    RECENT_HISTORY_MESSAGES: int = 10
    HISTORY_SUMMARY_TRIGGER: int = 14
    HISTORY_SUMMARY_CHAR_LIMIT: int = 12000
    ROUTER_USE_SEMANTIC_FALLBACK: bool = True
    ROUTER_SEMANTIC_THRESHOLD: float = 0.6
    ROUTER_MARGIN_THRESHOLD: float = 0.08
    MAX_MEMORY_ITEMS: int = 3
    MAX_ATTACHMENT_TEXT_CHARS: int = 12000
    BRAIN_ENABLE_ACTION_HANDOFF: bool = True

    @model_validator(mode="after")
    def apply_dynamic_runtime_defaults(self) -> "Settings":
        if self.OLLAMA_NUM_CTX is None:
            self.OLLAMA_NUM_CTX = recommend_ollama_num_ctx(
                use_gpu=self.USE_GPU,
                gpu_vram_gb=self.GPU_VRAM,
                hardware_target=self.HARDWARE_TARGET,
            )
        return self

    # Imagine tiers
    IMAGINE_FLUX_MODEL: str = "flux-schnell"     # Photoreal Quality
    IMAGINE_SDXL_MODEL: str = "sdxl-lightning"   # High Quality (Fast)
    IMAGINE_SD_MODEL: str = "stable-diffusion"   # Medium Quality (SD 1.5)
    IMAGINE_TINY_MODEL: str = "dalle-mini"       # Low Quality / CPU

    @computed_field
    @property
    def ACTIVE_MODEL(self) -> str:
        """Dynamically picks the best default brain based on detected hardware."""
        if self.HARDWARE_TARGET == "arm64":
            return self.LIGHT_MODEL
        if not self.USE_GPU:
            return self.MEDIUM_MODEL
        # For desktop GPU users, prefer the smarter 7B model as the default balance.
        return self.SMART_MODEL

    @computed_field
    @property
    def ACTIVE_IMAGINE_MODEL(self) -> str:
        """Dynamically picks the best imagine model."""
        if not self.USE_GPU:
            return self.IMAGINE_TINY_MODEL
        if self.GPU_VRAM >= 12.0:
            return self.IMAGINE_FLUX_MODEL
        if self.GPU_VRAM >= 5.5: 
            return self.IMAGINE_SDXL_MODEL
        return self.IMAGINE_SD_MODEL

    # --- Auth Settings ---
    SECRET_KEY: str = "bipod-ultra-secret-key-keep-it-local" # Recommend changing this in .env
    ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 60 * 24 * 7 # 7 days

settings = Settings()

# Ensure directories exist on startup
os.makedirs(settings.DOCUMENTS_DIR, exist_ok=True)
os.makedirs(settings.MEMORY_DIR, exist_ok=True)
os.makedirs(settings.VECTOR_DIR, exist_ok=True)
os.makedirs(settings.GENERATED_DIR, exist_ok=True)
os.makedirs(settings.UPLOADS_DIR, exist_ok=True)
